# Generated by Django 2.1.7 on 2019-02-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='complete_date',
            field=models.DateTimeField(default=0),
        ),
    ]
