# Generated by Django 2.1.7 on 2019-02-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20190214_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='complete_date',
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.User'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authentication.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
