# Generated by Django 2.1.7 on 2019-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20190225_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='current_status',
            field=models.CharField(choices=[('todo', 'todo'), ('in progress', 'in progress'), ('done', 'done')], default='todo', max_length=20),
        ),
    ]
